language: python
python:
  - '2.7'
  - '3.7'
install:
  - true
script:
  - true
deploy:
  - provider: pypi
    user: grktsh
    password:
      secure: GLoopAaI78K+RH++fT3hF8YBiDUR0Gz+oHijvSrjTBvfQbx8CLdqyVhhiFnJS4L/tZnzb3QQ+TrCydYFO+u/noANXHIjONbsk/8EyJzJvUhCsea6m9qo86MSEeJXn5HHBZxbAkbmJo8RAVtWhmanC+ADVSC0iSZA3Zsin0+VhAWx6Ty9WwfHB9/3BHP6uxNHvCE5UKoeS0INspZbqBYGiiZ5Hx7xTWkXhPCq5ixYn+1ItGg44iR0thNQRhyAGrdYGFYScnviYa9pqsQQWTKLjshMJyKV0q+FaA+c1aJYX2g75OTZVaAR20zgHI6fMYw3/i5ge9iE4jBjxOju/Ck8IPmm91q6EM0FzeQBnKT7zQ4jda93f1mBkH/Gt52ssJQUxB3s8jHQvoOJMp9ywy6qQQy0B5Mhp1Ty7dg12J44wokVdqJFaFI2ZIf3gC1DCj6L0mlpOdPiglaLDau6GWmQZrlGec++e9yBOJLdTpcQ6n7NEnwPAET4jZN8tUFkLHC9fRtzJKmJEW2nJsPHfWX9dlhiKjNjCCrdGkawyDZQdWfrctenXwWfxn3Y2x84MD0HgsmY6e1FZzYupPd+qtOzim+zIqte+PQ3n+3OP9aaFuYbMNahho540VB6GOqttv+ch6JeX4vD4yB7cFzuX17cGYzWKi3dUPUYe0HO4t3ERYY=
    server: https://test.pypi.org/legacy/
    distributions: sdist bdist_wheel
    skip_cleanup: true
    on:
      tags: true
      python: '3.7'
      repo: grktsh/my-python-packaging
  - provider: releases
    api_key:
      secure: hU/E7H87M3M6KlHvInEXfC816r16BrRopobgZ5QGdTBagcmwmkk8OVr0roDWowdXKhzLzCrwFWBf/ZUNb2NvKy1wMSQpztQf4yVWLNKuTo1l2PWqMEnHrDJwoCrSJmXWLKNFGkci9RlXR0ClOCP6TmhgENvBut1MHjJK+aqwhpCAy8W8XLBZomxSfpW2GIHJ4wp3tLHfIgRY1tu8vJmPT1WHRqNbMfX6N8iuQdhDS8VmgL5E4QNZtJZGMDz5nG1Q/WlJwin0jTc5gjBcfOVgqQoHkaohFLgcEp9bfziKVkOgFPFLlA79KLI+HmudUnPXf3nl/Jyb8TIVed5VRom1kUCEqjVB4jqjPBdhzH1g2zQTW62Q1hSM2cslXeR1gnUWmjy7ZDSfphB3VVSob1NWiF0WK9XOZbT8Cinale0Ajd8fbANt7j1UL+EvTHxbvLVMMSKCBDGC7zi/dfF97OpBCaaKKw2Sfa38S7vSGA8DgcA2FTH3RaZyF/8LJ3xm7SNOwZyKBs4qf80bkBNwUsXchAYjkS06PQZkiaVdMmM03xJNNjr1pQfa62l9G+Ik8KGYlQK7vPNVs430THeGGfK7iTt09eFHYzh0IUByKxo7xsHPMUugkTVFocjLKY6g8R0Xexdp5/EbTwpE4u3BoNk3xuJjCdWopJc5KKWG68/ISac=
    skip_cleanup: true
    on:
      python: '3.7'
      tags: true
